---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fleet-infra-cert-manager
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 15m
  path: ./manifests/security/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: fleet-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fleet-infra-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: fleet-infra-cert-manager
  serviceAccountName: kustomize-controller
  interval: 15m
  path: ./clusters/maktha/manifests/security/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: fleet-infra
