---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fleet-infra-hcloud-csi-driver
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 15m
  path: ./clusters/maktha/manifests/storage/hcloud-csi-driver
  prune: true
  sourceRef:
    kind: GitRepository
    name: fleet-infra
  decryption:
    provider: sops
    secretRef:
      name: fleet-infra-sops-age
