apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Flux
- ../../manifests/cd/flux
- manifests/flux/fleet-infra.yaml
- manifests/flux/fleet-infra.secret.yaml
- ../../manifests/cd/flux/notification

# hcloud
- manifests/hcloud-token.secret.yaml
- ../../manifests/storage/csi-driver-hcloud
