---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 6h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 6h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.7.x'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 6h
  targetNamespace: ingress-nginx
