apiVersion: v1
kind: Secret
metadata:
    name: flux-git-fleet-infra
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QsR72wZxc3bisfFEEecHh1fYahFl1Umrt+ZPyblGHVnTxk6q4kBg/CHdz9+u8jOz2Q+h7lrqLSaRNtgudMER32x0n1fy81kX3JNjP2CyXyfUeXg94ptyTvoGjVZci2aeV1WgFKQ1mNhCVPWqnWs/aJMJvuYhHvg=,iv:RbPr9fDse4/1dDnmaxa9xG2f3Yy/Z+QBK221qROfmVo=,tag:1t9rsNWJyEf82ck8k0zLqw==,type:str]
    identity.pub: ENC[AES256_GCM,data:nTyHF37GV9Hhvekwn3xWnmvgckjfG+Bkl06YAJkKdSNa6V95GOXoimKu6SPaeVMBVKZxJvihk5ug42huY1FiC768n1jaL6SqEZNGrl9XOrj9,iv:UwJ2LgCSLt+sbmrQpetlJZridYX2E8KtadXsCY229+M=,tag:B0wpXpwuPpkE97BbujZ0Nw==,type:str]
    known_hosts: ENC[AES256_GCM,data:jYHUMjgLJf2jMp/O3XGx61Ge6QC7Ri9ZGesrWIp/7481L5ODBPm9KbISmAnt3Lhr6OlojnFyjhMQXqkzhZkpPWb40BouTJP+1QRSqPJ+8SsR9FpiD2UYdWOc1iKZveH2+rYMeV+2fG63olARG9S6Y1WfJtnmdu1Yh0VfhZZlDRw5lTz1UFHQwiNcs010p5McVe2FZXtNVB0rPxJUiWc2S0pwO4fMXZvaa+3m,iv:g7iAP+tGAmqxTgYeGEHUbnVPpkii+6QBEgwoILg1WL0=,tag:b2/PRnbKvKeqAOzVc3WsVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1657w8lr7qkg8k22ya95avm88nf849dx6kc8w2gdaup7vz7ljv3ysmn0px7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdElKdVR6UTYyQUdSMXBT
            L2liVWV3b0tLL0Q1eGk0YWxocitqSUltLzNRCmljVm1JTklxaFVNRW5mTzJWOGhX
            a3IrS21LVld2YndLbFVxL3FpTG1pam8KLS0tIGthbXJPN2Q4dVBRSVFhU3pvTnlk
            b0tWbEZGSXZxZXNqaVJhTjJiL2lZSXcKgUEZ07RhN7ZJX9Ynvy6BplhMgfyHcyLZ
            swH03G1SmkUmGk68GXiNMotvF/wmQc6CJ4MyDRx0aHQBWRM35SQ88g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-27T19:20:38Z"
    mac: ENC[AES256_GCM,data:yQMKqDU8zQVr91IG3gtTQmEhGBf7/0waxT9Dqw1xooXdRyzXtMYPD3yURhZSfyZUvTMRIxMeDFxFYIHytY6mw+CIugGmPw7Amv5u6MnDmi3IpF4fca9JJGvp8oEe5/iYv+l8rPtfct+bj7IgfiijnpabHH5vjMJs9X4yhFhQVno=,iv:KgQJlWGvZOGkrj1eLG8oaDQoemdMCcC61mjOx2bT/L8=,tag:mlfOqUhkaoXcqm4ah18LhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
